# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Technical Exam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Technical Exam
  pod 'SecureDefaults', ‘1.0.7’
  pod 'Alamofire'
  pod 'RxSwift', ‘6.5.0’
  pod 'RxCocoa', ‘6.5.0’

  target 'Technical ExamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Technical ExamUITests' do
    # Pods for testing
  end

end
